// Автосгенерировано: переводы названий стран и городов для не-русских локалей.
// Ключ — канонiческое русское название (то, что реально хранится в БД и
// используется для фильтрации), значение — отображаемая подпись на нужном языке.
// Для 'ru' переводов нет — используется само каноническое название.

export type GeoLocale = 'en' | 'es' | 'de' | 'pt' | 'fr';

export const countryLabels: Record<GeoLocale, Record<string, string>> = {
  "en": {
    "Казахстан": "Kazakhstan",
    "Россия": "Russia",
    "Узбекистан": "Uzbekistan",
    "Киргизия": "Kyrgyzstan",
    "Таджикистан": "Tajikistan",
    "Туркменистан": "Turkmenistan",
    "Беларусь": "Belarus",
    "Украина": "Ukraine",
    "Молдова": "Moldova",
    "Грузия": "Georgia",
    "Армения": "Armenia",
    "Азербайджан": "Azerbaijan",
    "Турция": "Turkey",
    "Египет": "Egypt",
    "ОАЭ": "UAE",
    "Таиланд": "Thailand",
    "Вьетнам": "Vietnam",
    "Камбоджа": "Cambodia",
    "Лаос": "Laos",
    "Индия": "India",
    "Непал": "Nepal",
    "Маршалловы острова": "Marshall Islands",
    "Сейшелы": "Seychelles",
    "Маврикий": "Mauritius",
    "Мальдивы": "Maldives",
    "Шри-Ланка": "Sri Lanka",
    "Испания": "Spain",
    "Португалия": "Portugal",
    "Италия": "Italy",
    "Франция": "France",
    "Греция": "Greece",
    "Хорватия": "Croatia",
    "Болгария": "Bulgaria",
    "Румыния": "Romania",
    "Венгрия": "Hungary",
    "Чехия": "Czechia",
    "Австрия": "Austria",
    "Швейцария": "Switzerland",
    "Нидерланды": "Netherlands",
    "Бельгия": "Belgium",
    "Великобритания": "United Kingdom",
    "Ирландия": "Ireland",
    "Норвегия": "Norway",
    "Швеция": "Sweden",
    "Финляндия": "Finland",
    "Исландия": "Iceland",
    "Дания": "Denmark",
    "Польша": "Poland",
    "Литва": "Lithuania",
    "Латвия": "Latvia",
    "Эстония": "Estonia",
    "Германия": "Germany",
    "США": "USA",
    "Канада": "Canada",
    "Мексика": "Mexico",
    "Бразилия": "Brazil",
    "Аргентина": "Argentina",
    "Чили": "Chile",
    "Перу": "Peru",
    "Эквадор": "Ecuador",
    "Колумбия": "Colombia",
    "Венесуэла": "Venezuela",
    "Австралия": "Australia",
    "Новая Зеландия": "New Zealand",
    "Фиджи": "Fiji",
    "Вануату": "Vanuatu",
    "Корея": "South Korea",
    "Япония": "Japan",
    "Сингапур": "Singapore",
    "Малайзия": "Malaysia",
    "Индонезия": "Indonesia",
    "Филиппины": "Philippines",
    "Гонконг": "Hong Kong",
    "Тайвань": "Taiwan",
    "Монголия": "Mongolia",
    "Иран": "Iran",
    "Израиль": "Israel",
    "Иордания": "Jordan",
    "Ливан": "Lebanon",
    "Саудовская Аравия": "Saudi Arabia",
    "Катар": "Qatar",
    "Кувейт": "Kuwait",
    "Оман": "Oman",
    "Марокко": "Morocco",
    "Алжир": "Algeria",
    "Тунис": "Tunisia",
    "Ливия": "Libya",
    "Судан": "Sudan",
    "Кения": "Kenya",
    "Танзания": "Tanzania",
    "Уганда": "Uganda",
    "Эфиопия": "Ethiopia",
    "Ботсвана": "Botswana",
    "Зимбабве": "Zimbabwe",
    "Намибия": "Namibia",
    "ЮАР": "South Africa",
    "Мадагаскар": "Madagascar"
  },
  "es": {
    "Казахстан": "Kazajistán",
    "Россия": "Rusia",
    "Узбекистан": "Uzbekistán",
    "Киргизия": "Kirguistán",
    "Таджикистан": "Tayikistán",
    "Туркменистан": "Turkmenistán",
    "Беларусь": "Bielorrusia",
    "Украина": "Ucrania",
    "Молдова": "Moldavia",
    "Грузия": "Georgia",
    "Армения": "Armenia",
    "Азербайджан": "Azerbaiyán",
    "Турция": "Turquía",
    "Египет": "Egipto",
    "ОАЭ": "EAU",
    "Таиланд": "Tailandia",
    "Вьетнам": "Vietnam",
    "Камбоджа": "Camboya",
    "Лаос": "Laos",
    "Индия": "India",
    "Непал": "Nepal",
    "Маршалловы острова": "Islas Marshall",
    "Сейшелы": "Seychelles",
    "Маврикий": "Mauricio",
    "Мальдивы": "Maldivas",
    "Шри-Ланка": "Sri Lanka",
    "Испания": "España",
    "Португалия": "Portugal",
    "Италия": "Italia",
    "Франция": "Francia",
    "Греция": "Grecia",
    "Хорватия": "Croacia",
    "Болгария": "Bulgaria",
    "Румыния": "Rumanía",
    "Венгрия": "Hungría",
    "Чехия": "Chequia",
    "Австрия": "Austria",
    "Швейцария": "Suiza",
    "Нидерланды": "Países Bajos",
    "Бельгия": "Bélgica",
    "Великобритания": "Reino Unido",
    "Ирландия": "Irlanda",
    "Норвегия": "Noruega",
    "Швеция": "Suecia",
    "Финляндия": "Finlandia",
    "Исландия": "Islandia",
    "Дания": "Dinamarca",
    "Польша": "Polonia",
    "Литва": "Lituania",
    "Латвия": "Letonia",
    "Эстония": "Estonia",
    "Германия": "Alemania",
    "США": "EE. UU.",
    "Канада": "Canadá",
    "Мексика": "México",
    "Бразилия": "Brasil",
    "Аргентина": "Argentina",
    "Чили": "Chile",
    "Перу": "Perú",
    "Эквадор": "Ecuador",
    "Колумбия": "Colombia",
    "Венесуэла": "Venezuela",
    "Австралия": "Australia",
    "Новая Зеландия": "Nueva Zelanda",
    "Фиджи": "Fiyi",
    "Вануату": "Vanuatu",
    "Корея": "Corea del Sur",
    "Япония": "Japón",
    "Сингапур": "Singapur",
    "Малайзия": "Malasia",
    "Индонезия": "Indonesia",
    "Филиппины": "Filipinas",
    "Гонконг": "Hong Kong",
    "Тайвань": "Taiwán",
    "Монголия": "Mongolia",
    "Иран": "Irán",
    "Израиль": "Israel",
    "Иордания": "Jordania",
    "Ливан": "Líbano",
    "Саудовская Аравия": "Arabia Saudita",
    "Катар": "Catar",
    "Кувейт": "Kuwait",
    "Оман": "Omán",
    "Марокко": "Marruecos",
    "Алжир": "Argelia",
    "Тунис": "Túnez",
    "Ливия": "Libia",
    "Судан": "Sudán",
    "Кения": "Kenia",
    "Танзания": "Tanzania",
    "Уганда": "Uganda",
    "Эфиопия": "Etiopía",
    "Ботсвана": "Botsuana",
    "Зимбабве": "Zimbabue",
    "Намибия": "Namibia",
    "ЮАР": "Sudáfrica",
    "Мадагаскар": "Madagascar"
  },
  "de": {
    "Казахстан": "Kasachstan",
    "Россия": "Russland",
    "Узбекистан": "Usbekistan",
    "Киргизия": "Kirgisistan",
    "Таджикистан": "Tadschikistan",
    "Туркменистан": "Turkmenistan",
    "Беларусь": "Belarus",
    "Украина": "Ukraine",
    "Молдова": "Moldawien",
    "Грузия": "Georgien",
    "Армения": "Armenien",
    "Азербайджан": "Aserbaidschan",
    "Турция": "Türkei",
    "Египет": "Ägypten",
    "ОАЭ": "VAE",
    "Таиланд": "Thailand",
    "Вьетнам": "Vietnam",
    "Камбоджа": "Kambodscha",
    "Лаос": "Laos",
    "Индия": "Indien",
    "Непал": "Nepal",
    "Маршалловы острова": "Marshallinseln",
    "Сейшелы": "Seychellen",
    "Маврикий": "Mauritius",
    "Мальдивы": "Malediven",
    "Шри-Ланка": "Sri Lanka",
    "Испания": "Spanien",
    "Португалия": "Portugal",
    "Италия": "Italien",
    "Франция": "Frankreich",
    "Греция": "Griechenland",
    "Хорватия": "Kroatien",
    "Болгария": "Bulgarien",
    "Румыния": "Rumänien",
    "Венгрия": "Ungarn",
    "Чехия": "Tschechien",
    "Австрия": "Österreich",
    "Швейцария": "Schweiz",
    "Нидерланды": "Niederlande",
    "Бельгия": "Belgien",
    "Великобритания": "Vereinigtes Königreich",
    "Ирландия": "Irland",
    "Норвегия": "Norwegen",
    "Швеция": "Schweden",
    "Финляндия": "Finnland",
    "Исландия": "Island",
    "Дания": "Dänemark",
    "Польша": "Polen",
    "Литва": "Litauen",
    "Латвия": "Lettland",
    "Эстония": "Estland",
    "Германия": "Deutschland",
    "США": "USA",
    "Канада": "Kanada",
    "Мексика": "Mexiko",
    "Бразилия": "Brasilien",
    "Аргентина": "Argentinien",
    "Чили": "Chile",
    "Перу": "Peru",
    "Эквадор": "Ecuador",
    "Колумбия": "Kolumbien",
    "Венесуэла": "Venezuela",
    "Австралия": "Australien",
    "Новая Зеландия": "Neuseeland",
    "Фиджи": "Fidschi",
    "Вануату": "Vanuatu",
    "Корея": "Südkorea",
    "Япония": "Japan",
    "Сингапур": "Singapur",
    "Малайзия": "Malaysia",
    "Индонезия": "Indonesien",
    "Филиппины": "Philippinen",
    "Гонконг": "Hongkong",
    "Тайвань": "Taiwan",
    "Монголия": "Mongolei",
    "Иран": "Iran",
    "Израиль": "Israel",
    "Иордания": "Jordanien",
    "Ливан": "Libanon",
    "Саудовская Аравия": "Saudi-Arabien",
    "Катар": "Katar",
    "Кувейт": "Kuwait",
    "Оман": "Oman",
    "Марокко": "Marokko",
    "Алжир": "Algerien",
    "Тунис": "Tunesien",
    "Ливия": "Libyen",
    "Судан": "Sudan",
    "Кения": "Kenia",
    "Танзания": "Tansania",
    "Уганда": "Uganda",
    "Эфиопия": "Äthiopien",
    "Ботсвана": "Botswana",
    "Зимбабве": "Simbabwe",
    "Намибия": "Namibia",
    "ЮАР": "Südafrika",
    "Мадагаскар": "Madagaskar"
  },
  "pt": {
    "Казахстан": "Cazaquistão",
    "Россия": "Rússia",
    "Узбекистан": "Usbequistão",
    "Киргизия": "Quirguistão",
    "Таджикистан": "Tajiquistão",
    "Туркменистан": "Turcomenistão",
    "Беларусь": "Bielorrússia",
    "Украина": "Ucrânia",
    "Молдова": "Moldávia",
    "Грузия": "Geórgia",
    "Армения": "Armênia",
    "Азербайджан": "Azerbaijão",
    "Турция": "Turquia",
    "Египет": "Egito",
    "ОАЭ": "EAU",
    "Таиланд": "Tailândia",
    "Вьетнам": "Vietnã",
    "Камбоджа": "Camboja",
    "Лаос": "Laos",
    "Индия": "Índia",
    "Непал": "Nepal",
    "Маршалловы острова": "Ilhas Marshall",
    "Сейшелы": "Seicheles",
    "Маврикий": "Maurícia",
    "Мальдивы": "Maldivas",
    "Шри-Ланка": "Sri Lanka",
    "Испания": "Espanha",
    "Португалия": "Portugal",
    "Италия": "Itália",
    "Франция": "França",
    "Греция": "Grécia",
    "Хорватия": "Croácia",
    "Болгария": "Bulgária",
    "Румыния": "Romênia",
    "Венгрия": "Hungria",
    "Чехия": "Chéquia",
    "Австрия": "Áustria",
    "Швейцария": "Suíça",
    "Нидерланды": "Países Baixos",
    "Бельгия": "Bélgica",
    "Великобритания": "Reino Unido",
    "Ирландия": "Irlanda",
    "Норвегия": "Noruega",
    "Швеция": "Suécia",
    "Финляндия": "Finlândia",
    "Исландия": "Islândia",
    "Дания": "Dinamarca",
    "Польша": "Polônia",
    "Литва": "Lituânia",
    "Латвия": "Letônia",
    "Эстония": "Estônia",
    "Германия": "Alemanha",
    "США": "EUA",
    "Канада": "Canadá",
    "Мексика": "México",
    "Бразилия": "Brasil",
    "Аргентина": "Argentina",
    "Чили": "Chile",
    "Перу": "Peru",
    "Эквадор": "Equador",
    "Колумбия": "Colômbia",
    "Венесуэла": "Venezuela",
    "Австралия": "Austrália",
    "Новая Зеландия": "Nova Zelândia",
    "Фиджи": "Fiji",
    "Вануату": "Vanuatu",
    "Корея": "Coreia do Sul",
    "Япония": "Japão",
    "Сингапур": "Singapura",
    "Малайзия": "Malásia",
    "Индонезия": "Indonésia",
    "Филиппины": "Filipinas",
    "Гонконг": "Hong Kong",
    "Тайвань": "Taiwan",
    "Монголия": "Mongólia",
    "Иран": "Irã",
    "Израиль": "Israel",
    "Иордания": "Jordânia",
    "Ливан": "Líbano",
    "Саудовская Аравия": "Arábia Saudita",
    "Катар": "Catar",
    "Кувейт": "Kuwait",
    "Оман": "Omã",
    "Марокко": "Marrocos",
    "Алжир": "Argélia",
    "Тунис": "Tunísia",
    "Ливия": "Líbia",
    "Судан": "Sudão",
    "Кения": "Quênia",
    "Танзания": "Tanzânia",
    "Уганда": "Uganda",
    "Эфиопия": "Etiópia",
    "Ботсвана": "Botsuana",
    "Зимбабве": "Zimbábue",
    "Намибия": "Namíbia",
    "ЮАР": "África do Sul",
    "Мадагаскар": "Madagascar"
  },
  "fr": {
    "Казахстан": "Kazakhstan",
    "Россия": "Russie",
    "Узбекистан": "Ouzbékistan",
    "Киргизия": "Kirghizistan",
    "Таджикистан": "Tadjikistan",
    "Туркменистан": "Turkménistan",
    "Беларусь": "Biélorussie",
    "Украина": "Ukraine",
    "Молдова": "Moldavie",
    "Грузия": "Géorgie",
    "Армения": "Arménie",
    "Азербайджан": "Azerbaïdjan",
    "Турция": "Turquie",
    "Египет": "Égypte",
    "ОАЭ": "ÉAU",
    "Таиланд": "Thaïlande",
    "Вьетнам": "Vietnam",
    "Камбоджа": "Cambodge",
    "Лаос": "Laos",
    "Индия": "Inde",
    "Непал": "Népal",
    "Маршалловы острова": "Îles Marshall",
    "Сейшелы": "Seychelles",
    "Маврикий": "Maurice",
    "Мальдивы": "Maldives",
    "Шри-Ланка": "Sri Lanka",
    "Испания": "Espagne",
    "Португалия": "Portugal",
    "Италия": "Italie",
    "Франция": "France",
    "Греция": "Grèce",
    "Хорватия": "Croatie",
    "Болгария": "Bulgarie",
    "Румыния": "Roumanie",
    "Венгрия": "Hongrie",
    "Чехия": "Tchéquie",
    "Австрия": "Autriche",
    "Швейцария": "Suisse",
    "Нидерланды": "Pays-Bas",
    "Бельгия": "Belgique",
    "Великобритания": "Royaume-Uni",
    "Ирландия": "Irlande",
    "Норвегия": "Norvège",
    "Швеция": "Suède",
    "Финляндия": "Finlande",
    "Исландия": "Islande",
    "Дания": "Danemark",
    "Польша": "Pologne",
    "Литва": "Lituanie",
    "Латвия": "Lettonie",
    "Эстония": "Estonie",
    "Германия": "Allemagne",
    "США": "États-Unis",
    "Канада": "Canada",
    "Мексика": "Mexique",
    "Бразилия": "Brésil",
    "Аргентина": "Argentine",
    "Чили": "Chili",
    "Перу": "Pérou",
    "Эквадор": "Équateur",
    "Колумбия": "Colombie",
    "Венесуэла": "Venezuela",
    "Австралия": "Australie",
    "Новая Зеландия": "Nouvelle-Zélande",
    "Фиджи": "Fidji",
    "Вануату": "Vanuatu",
    "Корея": "Corée du Sud",
    "Япония": "Japon",
    "Сингапур": "Singapour",
    "Малайзия": "Malaisie",
    "Индонезия": "Indonésie",
    "Филиппины": "Philippines",
    "Гонконг": "Hong Kong",
    "Тайвань": "Taïwan",
    "Монголия": "Mongolie",
    "Иран": "Iran",
    "Израиль": "Israël",
    "Иордания": "Jordanie",
    "Ливан": "Liban",
    "Саудовская Аравия": "Arabie saoudite",
    "Катар": "Qatar",
    "Кувейт": "Koweït",
    "Оман": "Oman",
    "Марокко": "Maroc",
    "Алжир": "Algérie",
    "Тунис": "Tunisie",
    "Ливия": "Libye",
    "Судан": "Soudan",
    "Кения": "Kenya",
    "Танзания": "Tanzanie",
    "Уганда": "Ouganda",
    "Эфиопия": "Éthiopie",
    "Ботсвана": "Botswana",
    "Зимбабве": "Zimbabwe",
    "Намибия": "Namibie",
    "ЮАР": "Afrique du Sud",
    "Мадагаскар": "Madagascar"
  }
};

export const cityLabels: Record<GeoLocale, Record<string, string>> = {
  "en": {
    "Алматы": "Almaty",
    "Астана": "Astana",
    "Караганда": "Karaganda",
    "Шымкент": "Shymkent",
    "Атырау": "Atyrau",
    "Актау": "Aktau",
    "Москва": "Moscow",
    "Санкт-Петербург": "Saint Petersburg",
    "Новосибирск": "Novosibirsk",
    "Екатеринбург": "Yekaterinburg",
    "Казань": "Kazan",
    "Челябинск": "Chelyabinsk",
    "Ташкент": "Tashkent",
    "Самарканд": "Samarkand",
    "Бухара": "Bukhara",
    "Андижан": "Andijan",
    "Бишкек": "Bishkek",
    "Ош": "Osh",
    "Душанбе": "Dushanbe",
    "Худжанд": "Khujand",
    "Ашхабад": "Ashgabat",
    "Туркменбаши": "Turkmenbashi",
    "Минск": "Minsk",
    "Брест": "Brest",
    "Витебск": "Vitebsk",
    "Гомель": "Gomel",
    "Киев": "Kyiv",
    "Харьков": "Kharkiv",
    "Одесса": "Odesa",
    "Днепр": "Dnipro",
    "Кишинёв": "Chisinau",
    "Бельцы": "Balti",
    "Тбилиси": "Tbilisi",
    "Батуми": "Batumi",
    "Кутаиси": "Kutaisi",
    "Ереван": "Yerevan",
    "Гюмри": "Gyumri",
    "Баку": "Baku",
    "Гянджа": "Ganja",
    "Стамбул": "Istanbul",
    "Анталья": "Antalya",
    "Измир": "Izmir",
    "Каппадокия": "Cappadocia",
    "Газиантеп": "Gaziantep",
    "Каир": "Cairo",
    "Гиза": "Giza",
    "Луксор": "Luxor",
    "Асуан": "Aswan",
    "Шарм-эль-Шейх": "Sharm El Sheikh",
    "Дубай": "Dubai",
    "Абу-Даби": "Abu Dhabi",
    "Шарджа": "Sharjah",
    "Рас-эль-Хайма": "Ras al-Khaimah",
    "Бангкок": "Bangkok",
    "Паттайя": "Pattaya",
    "Пхукет": "Phuket",
    "Чиангмай": "Chiang Mai",
    "Ханой": "Hanoi",
    "Хошимин": "Ho Chi Minh City",
    "Хюе": "Hue",
    "Дананг": "Da Nang",
    "Пномпень": "Phnom Penh",
    "Сиемреап": "Siem Reap",
    "Сиануквиль": "Sihanoukville",
    "Вьентьян": "Vientiane",
    "Луангпхабанг": "Luang Prabang",
    "Дели": "Delhi",
    "Мумбаи": "Mumbai",
    "Джайпур": "Jaipur",
    "Варанаси": "Varanasi",
    "Агра": "Agra",
    "Катманду": "Kathmandu",
    "Поркхара": "Pokhara",
    "Бхактапур": "Bhaktapur",
    "Виктория": "Victoria",
    "Маэ": "Mahe",
    "Праслин": "Praslin",
    "Порт-Луи": "Port Louis",
    "Кюрпип": "Curepipe",
    "Мале": "Male",
    "Адду": "Addu",
    "Коломбо": "Colombo",
    "Канди": "Kandy",
    "Нуваэлия": "Nuwara Eliya",
    "Мадрид": "Madrid",
    "Барселона": "Barcelona",
    "Севилья": "Seville",
    "Валенсия": "Valencia",
    "Лиссабон": "Lisbon",
    "Порту": "Porto",
    "Альгарве": "Algarve",
    "Рим": "Rome",
    "Миланы": "Milan",
    "Венеция": "Venice",
    "Флоренция": "Florence",
    "Неаполь": "Naples",
    "Париж": "Paris",
    "Канны": "Cannes",
    "Монако": "Monaco",
    "Лион": "Lyon",
    "Марсель": "Marseille",
    "Афины": "Athens",
    "Салоники": "Thessaloniki",
    "Санторини": "Santorini",
    "Крит": "Crete",
    "Загреб": "Zagreb",
    "Дубровник": "Dubrovnik",
    "Сплит": "Split",
    "София": "Sofia",
    "Варна": "Varna",
    "Пловдив": "Plovdiv",
    "Бухарест": "Bucharest",
    "Брашов": "Brasov",
    "Клуж-Напока": "Cluj-Napoca",
    "Будапешт": "Budapest",
    "Дебрецен": "Debrecen",
    "Сегед": "Szeged",
    "Прага": "Prague",
    "Брно": "Brno",
    "Чески-Крумлов": "Cesky Krumlov",
    "Вена": "Vienna",
    "Зальцбург": "Salzburg",
    "Инсбрук": "Innsbruck",
    "Цюрих": "Zurich",
    "Люцерн": "Lucerne",
    "Базель": "Basel",
    "Амстердам": "Amsterdam",
    "Роттердам": "Rotterdam",
    "Утрехт": "Utrecht",
    "Брюссель": "Brussels",
    "Антверпен": "Antwerp",
    "Брюгге": "Bruges",
    "Лондон": "London",
    "Манчестер": "Manchester",
    "Эдинбург": "Edinburgh",
    "Дублин": "Dublin",
    "Корк": "Cork",
    "Осло": "Oslo",
    "Берген": "Bergen",
    "Тромсё": "Tromso",
    "Стокгольм": "Stockholm",
    "Гётеборг": "Gothenburg",
    "Мальме": "Malmo",
    "Хельсинки": "Helsinki",
    "Турку": "Turku",
    "Тампере": "Tampere",
    "Рейкьявик": "Reykjavik",
    "Акюрейри": "Akureyri",
    "Копенгаген": "Copenhagen",
    "Орхус": "Aarhus",
    "Варшава": "Warsaw",
    "Краков": "Krakow",
    "Вроцлав": "Wroclaw",
    "Вильнюс": "Vilnius",
    "Каунас": "Kaunas",
    "Рига": "Riga",
    "Юрмала": "Jurmala",
    "Таллин": "Tallinn",
    "Тарту": "Tartu",
    "Берлин": "Berlin",
    "Мюнхен": "Munich",
    "Кёльн": "Cologne",
    "Нью-Йорк": "New York",
    "Лос-Анджелес": "Los Angeles",
    "Чикаго": "Chicago",
    "Майами": "Miami",
    "Лас-Вегас": "Las Vegas",
    "Ванкувер": "Vancouver",
    "Торонто": "Toronto",
    "Монреаль": "Montreal",
    "Мехико": "Mexico City",
    "Канкун": "Cancun",
    "Плайя-дель-Кармен": "Playa del Carmen",
    "Рио-де-Жанейро": "Rio de Janeiro",
    "Сан-Паулу": "Sao Paulo",
    "Салвадор": "Salvador",
    "Буэнос-Айрес": "Buenos Aires",
    "Мендоза": "Mendoza",
    "Сантьяго": "Santiago",
    "Вальпараисо": "Valparaiso",
    "Лима": "Lima",
    "Куско": "Cusco",
    "Мачу-Пикчу": "Machu Picchu",
    "Кито": "Quito",
    "Гуаякиль": "Guayaquil",
    "Богота": "Bogota",
    "Медельин": "Medellin",
    "Каракас": "Caracas",
    "Марgarita": "Margarita",
    "Найроби": "Nairobi",
    "Момбаса": "Mombasa",
    "Дар-эс-Салам": "Dar es Salaam",
    "Камерон": "Cameron",
    "Кампала": "Kampala",
    "Форт-Портал": "Fort Portal",
    "Аддис-Абеба": "Addis Ababa",
    "Адама": "Adama",
    "Габороне": "Gaborone",
    "Касане": "Kasane",
    "Хараре": "Harare",
    "Виктория-Фолс": "Victoria Falls",
    "Виндхук": "Windhoek",
    "Суакопмунд": "Swakopmund",
    "Йоханнесбург": "Johannesburg",
    "Кейптаун": "Cape Town",
    "Претория": "Pretoria",
    "Антананариву": "Antananarivo",
    "Анциранана": "Antsiranana",
    "Алжир": "Algiers",
    "Оран": "Oran",
    "Тунис": "Tunis",
    "Сусс": "Sousse",
    "Сфакс": "Sfax",
    "Касабланка": "Casablanca",
    "Марракеш": "Marrakesh",
    "Фес": "Fez",
    "Сидней": "Sydney",
    "Мельбурн": "Melbourne",
    "Брисбен": "Brisbane",
    "Окленд": "Auckland",
    "Веллингтон": "Wellington",
    "Крайстчёрч": "Christchurch",
    "Сува": "Suva",
    "Нади": "Nadi",
    "Порт-Вила": "Port Vila",
    "Луганвиль": "Luganville",
    "Сеул": "Seoul",
    "Пусан": "Busan",
    "Инчхон": "Incheon",
    "Токио": "Tokyo",
    "Осака": "Osaka",
    "Киото": "Kyoto",
    "Хиросима": "Hiroshima",
    "Сингапур": "Singapore",
    "Куала-Лумпур": "Kuala Lumpur",
    "Джорджтаун": "George Town",
    "Джакарта": "Jakarta",
    "Бали": "Bali",
    "Йогякарта": "Yogyakarta",
    "Манила": "Manila",
    "Себу": "Cebu",
    "Давао": "Davao",
    "Гонконг": "Hong Kong",
    "Тайбэй": "Taipei",
    "Гаосюн": "Kaohsiung",
    "Улан-Батор": "Ulaanbaatar",
    "Тегеран": "Tehran",
    "Исфахан": "Isfahan",
    "Тель-Авив": "Tel Aviv",
    "Иерусалим": "Jerusalem",
    "Амман": "Amman",
    "Петра": "Petra",
    "Бейрут": "Beirut",
    "Триполи": "Tripoli",
    "Эр-Рияд": "Riyadh",
    "Джидда": "Jeddah",
    "Мекка": "Mecca",
    "Доха": "Doha",
    "Кувейт": "Kuwait City",
    "Маскат": "Muscat",
    "Салала": "Salalah"
  },
  "es": {
    "Алматы": "Almaty",
    "Астана": "Astana",
    "Караганда": "Karagandá",
    "Шымкент": "Shymkent",
    "Атырау": "Atyrau",
    "Актау": "Aktau",
    "Москва": "Moscú",
    "Санкт-Петербург": "San Petersburgo",
    "Новосибирск": "Novosibirsk",
    "Екатеринбург": "Ekaterimburgo",
    "Казань": "Kazán",
    "Челябинск": "Cheliábinsk",
    "Ташкент": "Taskent",
    "Самарканд": "Samarcanda",
    "Бухара": "Bujará",
    "Андижан": "Andiyán",
    "Бишкек": "Biskek",
    "Ош": "Osh",
    "Душанбе": "Dusambé",
    "Худжанд": "Khuyand",
    "Ашхабад": "Asjabad",
    "Туркменбаши": "Turkmenbashi",
    "Минск": "Minsk",
    "Брест": "Brest",
    "Витебск": "Vítebsk",
    "Гомель": "Gómel",
    "Киев": "Kiev",
    "Харьков": "Járkov",
    "Одесса": "Odesa",
    "Днепр": "Dniprό",
    "Кишинёв": "Chisináu",
    "Бельцы": "Bălți",
    "Тбилиси": "Tiflis",
    "Батуми": "Batumi",
    "Кутаиси": "Kutaisi",
    "Ереван": "Ereván",
    "Гюмри": "Guiumrí",
    "Баку": "Bakú",
    "Гянджа": "Ganyá",
    "Стамбул": "Estambul",
    "Анталья": "Antalya",
    "Измир": "Esmirna",
    "Каппадокия": "Capadocia",
    "Газиантеп": "Gaziantep",
    "Каир": "El Cairo",
    "Гиза": "Giza",
    "Луксор": "Luxor",
    "Асуан": "Asuán",
    "Шарм-эль-Шейх": "Sharm el-Sheij",
    "Дубай": "Dubái",
    "Абу-Даби": "Abu Dabi",
    "Шарджа": "Sharja",
    "Рас-эль-Хайма": "Ras al-Jaima",
    "Бангкок": "Bangkok",
    "Паттайя": "Pattaya",
    "Пхукет": "Phuket",
    "Чиангмай": "Chiang Mai",
    "Ханой": "Hanói",
    "Хошимин": "Ciudad Ho Chi Minh",
    "Хюе": "Huế",
    "Дананг": "Da Nang",
    "Пномпень": "Phnom Penh",
    "Сиемреап": "Siem Reap",
    "Сиануквиль": "Sihanoukville",
    "Вьентьян": "Vientián",
    "Луангпхабанг": "Luang Prabang",
    "Дели": "Delhi",
    "Мумбаи": "Bombay",
    "Джайпур": "Jaipur",
    "Варанаси": "Benarés",
    "Агра": "Agra",
    "Катманду": "Katmandú",
    "Поркхара": "Pokhara",
    "Бхактапур": "Bhaktapur",
    "Виктория": "Victoria",
    "Маэ": "Mahé",
    "Праслин": "Praslin",
    "Порт-Луи": "Port Louis",
    "Кюрпип": "Curepipe",
    "Мале": "Malé",
    "Адду": "Addu",
    "Коломбо": "Colombo",
    "Канди": "Kandy",
    "Нуваэлия": "Nuwara Eliya",
    "Мадрид": "Madrid",
    "Барселона": "Barcelona",
    "Севилья": "Sevilla",
    "Валенсия": "Valencia",
    "Лиссабон": "Lisboa",
    "Порту": "Oporto",
    "Альгарве": "Algarve",
    "Рим": "Roma",
    "Миланы": "Milán",
    "Венеция": "Venecia",
    "Флоренция": "Florencia",
    "Неаполь": "Nápoles",
    "Париж": "París",
    "Канны": "Cannes",
    "Монако": "Mónaco",
    "Лион": "Lyon",
    "Марсель": "Marsella",
    "Афины": "Atenas",
    "Салоники": "Salónica",
    "Санторини": "Santorini",
    "Крит": "Creta",
    "Загреб": "Zagreb",
    "Дубровник": "Dubrovnik",
    "Сплит": "Split",
    "София": "Sofía",
    "Варна": "Varna",
    "Пловдив": "Plovdiv",
    "Бухарест": "Bucarest",
    "Брашов": "Brasov",
    "Клуж-Напока": "Cluj-Napoca",
    "Будапешт": "Budapest",
    "Дебрецен": "Debrecen",
    "Сегед": "Szeged",
    "Прага": "Praga",
    "Брно": "Brno",
    "Чески-Крумлов": "Cesky Krumlov",
    "Вена": "Viena",
    "Зальцбург": "Salzburgo",
    "Инсбрук": "Innsbruck",
    "Цюрих": "Zúrich",
    "Люцерн": "Lucerna",
    "Базель": "Basilea",
    "Амстердам": "Ámsterdam",
    "Роттердам": "Róterdam",
    "Утрехт": "Utrecht",
    "Брюссель": "Bruselas",
    "Антверпен": "Amberes",
    "Брюгге": "Brujas",
    "Лондон": "Londres",
    "Манчестер": "Mánchester",
    "Эдинбург": "Edimburgo",
    "Дублин": "Dublín",
    "Корк": "Cork",
    "Осло": "Oslo",
    "Берген": "Bergen",
    "Тромсё": "Tromsø",
    "Стокгольм": "Estocolmo",
    "Гётеборг": "Gotemburgo",
    "Мальме": "Malmö",
    "Хельсинки": "Helsinki",
    "Турку": "Turku",
    "Тампере": "Tampere",
    "Рейкьявик": "Reikiavik",
    "Акюрейри": "Akureyri",
    "Копенгаген": "Copenhague",
    "Орхус": "Aarhus",
    "Варшава": "Varsovia",
    "Краков": "Cracovia",
    "Вроцлав": "Breslavia",
    "Вильнюс": "Vilna",
    "Каунас": "Kaunas",
    "Рига": "Riga",
    "Юрмала": "Jurmala",
    "Таллин": "Tallin",
    "Тарту": "Tartu",
    "Берлин": "Berlín",
    "Мюнхен": "Múnich",
    "Кёльн": "Colonia",
    "Нью-Йорк": "Nueva York",
    "Лос-Анджелес": "Los Ángeles",
    "Чикаго": "Chicago",
    "Майами": "Miami",
    "Лас-Вегас": "Las Vegas",
    "Ванкувер": "Vancouver",
    "Торонто": "Toronto",
    "Монреаль": "Montreal",
    "Мехико": "Ciudad de México",
    "Канкун": "Cancún",
    "Плайя-дель-Кармен": "Playa del Carmen",
    "Рио-де-Жанейро": "Río de Janeiro",
    "Сан-Паулу": "São Paulo",
    "Салвадор": "Salvador",
    "Буэнос-Айрес": "Buenos Aires",
    "Мендоза": "Mendoza",
    "Сантьяго": "Santiago",
    "Вальпараисо": "Valparaíso",
    "Лима": "Lima",
    "Куско": "Cusco",
    "Мачу-Пикчу": "Machu Picchu",
    "Кито": "Quito",
    "Гуаякиль": "Guayaquil",
    "Богота": "Bogotá",
    "Медельин": "Medellín",
    "Каракас": "Caracas",
    "Марgarita": "Margarita",
    "Найроби": "Nairobi",
    "Момбаса": "Mombasa",
    "Дар-эс-Салам": "Dar es Salam",
    "Камерон": "Camerún",
    "Кампала": "Kampala",
    "Форт-Портал": "Fort Portal",
    "Аддис-Абеба": "Adís Abeba",
    "Адама": "Adama",
    "Габороне": "Gaborone",
    "Касане": "Kasane",
    "Хараре": "Harare",
    "Виктория-Фолс": "Cataratas Victoria",
    "Виндхук": "Windhoek",
    "Суакопмунд": "Swakopmund",
    "Йоханнесбург": "Johannesburgo",
    "Кейптаун": "Ciudad del Cabo",
    "Претория": "Pretoria",
    "Антананариву": "Antananarivo",
    "Анциранана": "Antsiranana",
    "Алжир": "Argel",
    "Оран": "Orán",
    "Тунис": "Túnez",
    "Сусс": "Susa",
    "Сфакс": "Sfax",
    "Касабланка": "Casablanca",
    "Марракеш": "Marrakech",
    "Фес": "Fez",
    "Сидней": "Sídney",
    "Мельбурн": "Melbourne",
    "Брисбен": "Brisbane",
    "Окленд": "Auckland",
    "Веллингтон": "Wellington",
    "Крайстчёрч": "Christchurch",
    "Сува": "Suva",
    "Нади": "Nadi",
    "Порт-Вила": "Port Vila",
    "Луганвиль": "Luganville",
    "Сеул": "Seúl",
    "Пусан": "Busán",
    "Инчхон": "Incheon",
    "Токио": "Tokio",
    "Осака": "Osaka",
    "Киото": "Kioto",
    "Хиросима": "Hiroshima",
    "Сингапур": "Singapur",
    "Куала-Лумпур": "Kuala Lumpur",
    "Джорджтаун": "George Town",
    "Джакарта": "Yakarta",
    "Бали": "Bali",
    "Йогякарта": "Yogyakarta",
    "Манила": "Manila",
    "Себу": "Cebú",
    "Давао": "Davao",
    "Гонконг": "Hong Kong",
    "Тайбэй": "Taipéi",
    "Гаосюн": "Kaohsiung",
    "Улан-Батор": "Ulán Bator",
    "Тегеран": "Teherán",
    "Исфахан": "Isfahán",
    "Тель-Авив": "Tel Aviv",
    "Иерусалим": "Jerusalén",
    "Амман": "Amán",
    "Петра": "Petra",
    "Бейрут": "Beirut",
    "Триполи": "Trípoli",
    "Эр-Рияд": "Riad",
    "Джидда": "Yeda",
    "Мекка": "La Meca",
    "Доха": "Doha",
    "Кувейт": "Ciudad de Kuwait",
    "Маскат": "Mascate",
    "Салала": "Salalah"
  },
  "de": {
    "Алматы": "Almaty",
    "Астана": "Astana",
    "Караганда": "Karaganda",
    "Шымкент": "Schymkent",
    "Атырау": "Atyrau",
    "Актау": "Aktau",
    "Москва": "Moskau",
    "Санкт-Петербург": "Sankt Petersburg",
    "Новосибирск": "Novosibirsk",
    "Екатеринбург": "Jekaterinburg",
    "Казань": "Kasan",
    "Челябинск": "Tscheljabinsk",
    "Ташкент": "Taschkent",
    "Самарканд": "Samarkand",
    "Бухара": "Buchara",
    "Андижан": "Andijan",
    "Бишкек": "Bischkek",
    "Ош": "Osch",
    "Душанбе": "Duschanbe",
    "Худжанд": "Chudschand",
    "Ашхабад": "Aşgabat",
    "Туркменбаши": "Turkmenbaschy",
    "Минск": "Minsk",
    "Брест": "Brest",
    "Витебск": "Witebsk",
    "Гомель": "Gomel",
    "Киев": "Kiew",
    "Харьков": "Charkiw",
    "Одесса": "Odessa",
    "Днепр": "Dnipro",
    "Кишинёв": "Chișinău",
    "Бельцы": "Bălți",
    "Тбилиси": "Tiflis",
    "Батуми": "Batumi",
    "Кутаиси": "Kutaissi",
    "Ереван": "Eriwan",
    "Гюмри": "Gjumri",
    "Баку": "Baku",
    "Гянджа": "Gəncə",
    "Стамбул": "Istanbul",
    "Анталья": "Antalya",
    "Измир": "Izmir",
    "Каппадокия": "Kappadokien",
    "Газиантеп": "Gaziantep",
    "Каир": "Kairo",
    "Гиза": "Gizeh",
    "Луксор": "Luxor",
    "Асуан": "Assuan",
    "Шарм-эль-Шейх": "Scharm el-Scheich",
    "Дубай": "Dubai",
    "Абу-Даби": "Abu Dhabi",
    "Шарджа": "Sharjah",
    "Рас-эль-Хайма": "Ras al-Chaima",
    "Бангкок": "Bangkok",
    "Паттайя": "Pattaya",
    "Пхукет": "Phuket",
    "Чиангмай": "Chiang Mai",
    "Ханой": "Hanoi",
    "Хошимин": "Ho-Chi-Minh-Stadt",
    "Хюе": "Huế",
    "Дананг": "Da Nang",
    "Пномпень": "Phnom Penh",
    "Сиемреап": "Siem Reap",
    "Сиануквиль": "Sihanoukville",
    "Вьентьян": "Vientiane",
    "Луангпхабанг": "Luang Prabang",
    "Дели": "Delhi",
    "Мумбаи": "Mumbai",
    "Джайпур": "Jaipur",
    "Варанаси": "Varanasi",
    "Агра": "Agra",
    "Катманду": "Kathmandu",
    "Поркхара": "Pokhara",
    "Бхактапур": "Bhaktapur",
    "Виктория": "Victoria",
    "Маэ": "Mahé",
    "Праслин": "Praslin",
    "Порт-Луи": "Port Louis",
    "Кюрпип": "Curepipe",
    "Мале": "Malé",
    "Адду": "Addu",
    "Коломбо": "Colombo",
    "Канди": "Kandy",
    "Нуваэлия": "Nuwara Eliya",
    "Мадрид": "Madrid",
    "Барселона": "Barcelona",
    "Севилья": "Sevilla",
    "Валенсия": "Valencia",
    "Лиссабон": "Lissabon",
    "Порту": "Porto",
    "Альгарве": "Algarve",
    "Рим": "Rom",
    "Миланы": "Mailand",
    "Венеция": "Venedig",
    "Флоренция": "Florenz",
    "Неаполь": "Neapel",
    "Париж": "Paris",
    "Канны": "Cannes",
    "Монако": "Monaco",
    "Лион": "Lyon",
    "Марсель": "Marseille",
    "Афины": "Athen",
    "Салоники": "Thessaloniki",
    "Санторини": "Santorin",
    "Крит": "Kreta",
    "Загреб": "Zagreb",
    "Дубровник": "Dubrovnik",
    "Сплит": "Split",
    "София": "Sofia",
    "Варна": "Varna",
    "Пловдив": "Plovdiv",
    "Бухарест": "Bukarest",
    "Брашов": "Brașov",
    "Клуж-Напока": "Cluj-Napoca",
    "Будапешт": "Budapest",
    "Дебрецен": "Debrecen",
    "Сегед": "Szeged",
    "Прага": "Prag",
    "Брно": "Brünn",
    "Чески-Крумлов": "Český Krumlov",
    "Вена": "Wien",
    "Зальцбург": "Salzburg",
    "Инсбрук": "Innsbruck",
    "Цюрих": "Zürich",
    "Люцерн": "Luzern",
    "Базель": "Basel",
    "Амстердам": "Amsterdam",
    "Роттердам": "Rotterdam",
    "Утрехт": "Utrecht",
    "Брюссель": "Brüssel",
    "Антверпен": "Antwerpen",
    "Брюгге": "Brügge",
    "Лондон": "London",
    "Манчестер": "Manchester",
    "Эдинбург": "Edinburgh",
    "Дублин": "Dublin",
    "Корк": "Cork",
    "Осло": "Oslo",
    "Берген": "Bergen",
    "Тромсё": "Tromsø",
    "Стокгольм": "Stockholm",
    "Гётеборг": "Göteborg",
    "Мальме": "Malmö",
    "Хельсинки": "Helsinki",
    "Турку": "Turku",
    "Тампере": "Tampere",
    "Рейкьявик": "Reykjavík",
    "Акюрейри": "Akureyri",
    "Копенгаген": "Kopenhagen",
    "Орхус": "Aarhus",
    "Варшава": "Warschau",
    "Краков": "Krakau",
    "Вроцлав": "Breslau",
    "Вильнюс": "Vilnius",
    "Каунас": "Kaunas",
    "Рига": "Riga",
    "Юрмала": "Jurmala",
    "Таллин": "Tallinn",
    "Тарту": "Tartu",
    "Берлин": "Berlin",
    "Мюнхен": "München",
    "Кёльн": "Köln",
    "Нью-Йорк": "New York",
    "Лос-Анджелес": "Los Angeles",
    "Чикаго": "Chicago",
    "Майами": "Miami",
    "Лас-Вегас": "Las Vegas",
    "Ванкувер": "Vancouver",
    "Торонто": "Toronto",
    "Монреаль": "Montreal",
    "Мехико": "Mexiko-Stadt",
    "Канкун": "Cancún",
    "Плайя-дель-Кармен": "Playa del Carmen",
    "Рио-де-Жанейро": "Rio de Janeiro",
    "Сан-Паулу": "São Paulo",
    "Салвадор": "Salvador",
    "Буэнос-Айрес": "Buenos Aires",
    "Мендоза": "Mendoza",
    "Сантьяго": "Santiago",
    "Вальпараисо": "Valparaíso",
    "Лима": "Lima",
    "Куско": "Cusco",
    "Мачу-Пикчу": "Machu Picchu",
    "Кито": "Quito",
    "Гуаякиль": "Guayaquil",
    "Богота": "Bogotá",
    "Медельин": "Medellín",
    "Каракас": "Caracas",
    "Марgarita": "Margarita",
    "Найроби": "Nairobi",
    "Момбаса": "Mombasa",
    "Дар-эс-Салам": "Daressalam",
    "Камерон": "Cameron",
    "Кампала": "Kampala",
    "Форт-Портал": "Fort Portal",
    "Аддис-Абеба": "Addis Abeba",
    "Адама": "Adama",
    "Габороне": "Gaborone",
    "Касане": "Kasane",
    "Хараре": "Harare",
    "Виктория-Фолс": "Victoriafälle",
    "Виндхук": "Windhoek",
    "Суакопмунд": "Swakopmund",
    "Йоханнесбург": "Johannesburg",
    "Кейптаун": "Kapstadt",
    "Претория": "Pretoria",
    "Антананариву": "Antananarivo",
    "Анциранана": "Antsiranana",
    "Алжир": "Algier",
    "Оран": "Oran",
    "Тунис": "Tunis",
    "Сусс": "Sousse",
    "Сфакс": "Sfax",
    "Касабланка": "Casablanca",
    "Марракеш": "Marrakesch",
    "Фес": "Fès",
    "Сидней": "Sydney",
    "Мельбурн": "Melbourne",
    "Брисбен": "Brisbane",
    "Окленд": "Auckland",
    "Веллингтон": "Wellington",
    "Крайстчёрч": "Christchurch",
    "Сува": "Suva",
    "Нади": "Nadi",
    "Порт-Вила": "Port Vila",
    "Луганвиль": "Luganville",
    "Сеул": "Seoul",
    "Пусан": "Busan",
    "Инчхон": "Incheon",
    "Токио": "Tokio",
    "Осака": "Osaka",
    "Киото": "Kyoto",
    "Хиросима": "Hiroshima",
    "Сингапур": "Singapur",
    "Куала-Лумпур": "Kuala Lumpur",
    "Джорджтаун": "George Town",
    "Джакарта": "Jakarta",
    "Бали": "Bali",
    "Йогякарта": "Yogyakarta",
    "Манила": "Manila",
    "Себу": "Cebu",
    "Давао": "Davao",
    "Гонконг": "Hongkong",
    "Тайбэй": "Taipeh",
    "Гаосюн": "Kaohsiung",
    "Улан-Батор": "Ulaanbaatar",
    "Тегеран": "Teheran",
    "Исфахан": "Isfahan",
    "Тель-Авив": "Tel Aviv",
    "Иерусалим": "Jerusalem",
    "Амман": "Amman",
    "Петра": "Petra",
    "Бейрут": "Beirut",
    "Триполи": "Tripoli",
    "Эр-Рияд": "Riad",
    "Джидда": "Dschidda",
    "Мекка": "Mekka",
    "Доха": "Doha",
    "Кувейт": "Kuwait-Stadt",
    "Маскат": "Maskat",
    "Салала": "Salalah"
  },
  "pt": {
    "Алматы": "Almaty",
    "Астана": "Astana",
    "Караганда": "Karaganda",
    "Шымкент": "Shymkent",
    "Атырау": "Atyrau",
    "Актау": "Aktau",
    "Москва": "Moscou",
    "Санкт-Петербург": "São Petersburgo",
    "Новосибирск": "Novosibirsk",
    "Екатеринбург": "Ecaterimburgo",
    "Казань": "Cazã",
    "Челябинск": "Cheliabinsk",
    "Ташкент": "Tasquente",
    "Самарканд": "Samarcanda",
    "Бухара": "Bucara",
    "Андижан": "Andijã",
    "Бишкек": "Bisqueque",
    "Ош": "Oche",
    "Душанбе": "Duchambe",
    "Худжанд": "Khujand",
    "Ашхабад": "Asgabate",
    "Туркменбаши": "Turquemenbachi",
    "Минск": "Minsk",
    "Брест": "Brest",
    "Витебск": "Vitebsk",
    "Гомель": "Gomel",
    "Киев": "Kiev",
    "Харьков": "Carcóvia",
    "Одесса": "Odessa",
    "Днепр": "Dnipro",
    "Кишинёв": "Chisinau",
    "Бельцы": "Bălți",
    "Тбилиси": "Tbilisi",
    "Батуми": "Batumi",
    "Кутаиси": "Cutaisi",
    "Ереван": "Erevã",
    "Гюмри": "Guimri",
    "Баку": "Bacu",
    "Гянджа": "Ganja",
    "Стамбул": "Istambul",
    "Анталья": "Antália",
    "Измир": "Esmirna",
    "Каппадокия": "Capadócia",
    "Газиантеп": "Gaziantep",
    "Каир": "Cairo",
    "Гиза": "Gizé",
    "Луксор": "Luxor",
    "Асуан": "Assuã",
    "Шарм-эль-Шейх": "Sharm el-Sheikh",
    "Дубай": "Dubai",
    "Абу-Даби": "Abu Dhabi",
    "Шарджа": "Sharjah",
    "Рас-эль-Хайма": "Ras al-Khaimah",
    "Бангкок": "Banguecoque",
    "Паттайя": "Pattaya",
    "Пхукет": "Phuket",
    "Чиангмай": "Chiang Mai",
    "Ханой": "Hanói",
    "Хошимин": "Cidade de Ho Chi Minh",
    "Хюе": "Huế",
    "Дананг": "Da Nang",
    "Пномпень": "Phnom Penh",
    "Сиемреап": "Siem Reap",
    "Сиануквиль": "Sihanoukville",
    "Вьентьян": "Vientiane",
    "Луангпхабанг": "Luang Prabang",
    "Дели": "Deli",
    "Мумбаи": "Mumbai",
    "Джайпур": "Jaipur",
    "Варанаси": "Varanasi",
    "Агра": "Agra",
    "Катманду": "Catmandu",
    "Поркхара": "Pokhara",
    "Бхактапур": "Bhaktapur",
    "Виктория": "Vitória",
    "Маэ": "Mahé",
    "Праслин": "Praslin",
    "Порт-Луи": "Port Louis",
    "Кюрпип": "Curepipe",
    "Мале": "Malé",
    "Адду": "Addu",
    "Коломбо": "Colombo",
    "Канди": "Kandy",
    "Нуваэлия": "Nuwara Eliya",
    "Мадрид": "Madrid",
    "Барселона": "Barcelona",
    "Севилья": "Sevilha",
    "Валенсия": "Valência",
    "Лиссабон": "Lisboa",
    "Порту": "Porto",
    "Альгарве": "Algarve",
    "Рим": "Roma",
    "Миланы": "Milão",
    "Венеция": "Veneza",
    "Флоренция": "Florença",
    "Неаполь": "Nápoles",
    "Париж": "Paris",
    "Канны": "Cannes",
    "Монако": "Mônaco",
    "Лион": "Lyon",
    "Марсель": "Marselha",
    "Афины": "Atenas",
    "Салоники": "Salónica",
    "Санторини": "Santorini",
    "Крит": "Creta",
    "Загреб": "Zagrebe",
    "Дубровник": "Dubrovnik",
    "Сплит": "Split",
    "София": "Sófia",
    "Варна": "Varna",
    "Пловдив": "Plovdiv",
    "Бухарест": "Bucareste",
    "Брашов": "Brasov",
    "Клуж-Напока": "Cluj-Napoca",
    "Будапешт": "Budapeste",
    "Дебрецен": "Debrecen",
    "Сегед": "Szeged",
    "Прага": "Praga",
    "Брно": "Brno",
    "Чески-Крумлов": "Cesky Krumlov",
    "Вена": "Viena",
    "Зальцбург": "Salzburgo",
    "Инсбрук": "Innsbruque",
    "Цюрих": "Zurique",
    "Люцерн": "Lucerna",
    "Базель": "Basileia",
    "Амстердам": "Amsterdã",
    "Роттердам": "Roterdã",
    "Утрехт": "Utreque",
    "Брюссель": "Bruxelas",
    "Антверпен": "Antuérpia",
    "Брюгге": "Bruges",
    "Лондон": "Londres",
    "Манчестер": "Manchester",
    "Эдинбург": "Edimburgo",
    "Дублин": "Dublin",
    "Корк": "Cork",
    "Осло": "Oslo",
    "Берген": "Bergen",
    "Тромсё": "Tromsø",
    "Стокгольм": "Estocolmo",
    "Гётеборг": "Gotemburgo",
    "Мальме": "Malmö",
    "Хельсинки": "Helsínquia",
    "Турку": "Turku",
    "Тампере": "Tampere",
    "Рейкьявик": "Reykjavik",
    "Акюрейри": "Akureyri",
    "Копенгаген": "Copenhague",
    "Орхус": "Aarhus",
    "Варшава": "Varsóvia",
    "Краков": "Cracóvia",
    "Вроцлав": "Breslávia",
    "Вильнюс": "Vilnius",
    "Каунас": "Kaunas",
    "Рига": "Riga",
    "Юрмала": "Jurmala",
    "Таллин": "Taline",
    "Тарту": "Tartu",
    "Берлин": "Berlim",
    "Мюнхен": "Munique",
    "Кёльн": "Colônia",
    "Нью-Йорк": "Nova York",
    "Лос-Анджелес": "Los Angeles",
    "Чикаго": "Chicago",
    "Майами": "Miami",
    "Лас-Вегас": "Las Vegas",
    "Ванкувер": "Vancouver",
    "Торонто": "Toronto",
    "Монреаль": "Montreal",
    "Мехико": "Cidade do México",
    "Канкун": "Cancún",
    "Плайя-дель-Кармен": "Playa del Carmen",
    "Рио-де-Жанейро": "Rio de Janeiro",
    "Сан-Паулу": "São Paulo",
    "Салвадор": "Salvador",
    "Буэнос-Айрес": "Buenos Aires",
    "Мендоза": "Mendoza",
    "Сантьяго": "Santiago",
    "Вальпараисо": "Valparaíso",
    "Лима": "Lima",
    "Куско": "Cusco",
    "Мачу-Пикчу": "Machu Picchu",
    "Кито": "Quito",
    "Гуаякиль": "Guayaquil",
    "Богота": "Bogotá",
    "Медельин": "Medellín",
    "Каракас": "Caracas",
    "Марgarita": "Margarita",
    "Найроби": "Nairóbi",
    "Момбаса": "Mombaça",
    "Дар-эс-Салам": "Dar es Salaam",
    "Камерон": "Camarões",
    "Кампала": "Campala",
    "Форт-Портал": "Fort Portal",
    "Аддис-Абеба": "Adis Abeba",
    "Адама": "Adama",
    "Габороне": "Gaborone",
    "Касане": "Kasane",
    "Хараре": "Harare",
    "Виктория-Фолс": "Cataratas Vitória",
    "Виндхук": "Windhoek",
    "Суакопмунд": "Swakopmund",
    "Йоханнесбург": "Joanesburgo",
    "Кейптаун": "Cidade do Cabo",
    "Претория": "Pretória",
    "Антананариву": "Antananarivo",
    "Анциранана": "Antsiranana",
    "Алжир": "Argel",
    "Оран": "Orã",
    "Тунис": "Tunes",
    "Сусс": "Sousse",
    "Сфакс": "Sfax",
    "Касабланка": "Casablanca",
    "Марракеш": "Marraquexe",
    "Фес": "Fez",
    "Сидней": "Sydney",
    "Мельбурн": "Melbourne",
    "Брисбен": "Brisbane",
    "Окленд": "Auckland",
    "Веллингтон": "Wellington",
    "Крайстчёрч": "Christchurch",
    "Сува": "Suva",
    "Нади": "Nadi",
    "Порт-Вила": "Port Vila",
    "Луганвиль": "Luganville",
    "Сеул": "Seul",
    "Пусан": "Busan",
    "Инчхон": "Incheon",
    "Токио": "Tóquio",
    "Осака": "Osaka",
    "Киото": "Kyoto",
    "Хиросима": "Hiroshima",
    "Сингапур": "Singapura",
    "Куала-Лумпур": "Kuala Lumpur",
    "Джорджтаун": "George Town",
    "Джакарта": "Jacarta",
    "Бали": "Bali",
    "Йогякарта": "Yogyakarta",
    "Манила": "Manila",
    "Себу": "Cebu",
    "Давао": "Davao",
    "Гонконг": "Hong Kong",
    "Тайбэй": "Taipei",
    "Гаосюн": "Kaohsiung",
    "Улан-Батор": "Ulã Bator",
    "Тегеран": "Teerã",
    "Исфахан": "Isfahan",
    "Тель-Авив": "Tel Aviv",
    "Иерусалим": "Jerusalém",
    "Амман": "Amã",
    "Петра": "Petra",
    "Бейрут": "Beirute",
    "Триполи": "Trípoli",
    "Эр-Рияд": "Riade",
    "Джидда": "Jidá",
    "Мекка": "Meca",
    "Доха": "Doha",
    "Кувейт": "Cidade do Kuwait",
    "Маскат": "Mascate",
    "Салала": "Salalah"
  },
  "fr": {
    "Алматы": "Almaty",
    "Астана": "Astana",
    "Караганда": "Karaganda",
    "Шымкент": "Chymkent",
    "Атырау": "Atyraou",
    "Актау": "Aktaou",
    "Москва": "Moscou",
    "Санкт-Петербург": "Saint-Pétersbourg",
    "Новосибирск": "Novossibirsk",
    "Екатеринбург": "Iekaterinbourg",
    "Казань": "Kazan",
    "Челябинск": "Tcheliabinsk",
    "Ташкент": "Tachkent",
    "Самарканд": "Samarcande",
    "Бухара": "Boukhara",
    "Андижан": "Andijan",
    "Бишкек": "Bichkek",
    "Ош": "Och",
    "Душанбе": "Douchanbé",
    "Худжанд": "Khoudjand",
    "Ашхабад": "Achgabat",
    "Туркменбаши": "Turkmenbachi",
    "Минск": "Minsk",
    "Брест": "Brest",
    "Витебск": "Vitebsk",
    "Гомель": "Homel",
    "Киев": "Kiev",
    "Харьков": "Kharkiv",
    "Одесса": "Odessa",
    "Днепр": "Dnipro",
    "Кишинёв": "Chișinău",
    "Бельцы": "Bălți",
    "Тбилиси": "Tbilissi",
    "Батуми": "Batoumi",
    "Кутаиси": "Koutaïssi",
    "Ереван": "Erevan",
    "Гюмри": "Gyumri",
    "Баку": "Bakou",
    "Гянджа": "Gandja",
    "Стамбул": "Istanbul",
    "Анталья": "Antalya",
    "Измир": "Izmir",
    "Каппадокия": "Cappadoce",
    "Газиантеп": "Gaziantep",
    "Каир": "Le Caire",
    "Гиза": "Gizeh",
    "Луксор": "Louxor",
    "Асуан": "Assouan",
    "Шарм-эль-Шейх": "Charm el-Cheikh",
    "Дубай": "Dubaï",
    "Абу-Даби": "Abou Dabi",
    "Шарджа": "Charjah",
    "Рас-эль-Хайма": "Ras el-Khaïmah",
    "Бангкок": "Bangkok",
    "Паттайя": "Pattaya",
    "Пхукет": "Phuket",
    "Чиангмай": "Chiang Mai",
    "Ханой": "Hanoï",
    "Хошимин": "Hô Chi Minh-Ville",
    "Хюе": "Huế",
    "Дананг": "Da Nang",
    "Пномпень": "Phnom Penh",
    "Сиемреап": "Siem Reap",
    "Сиануквиль": "Sihanoukville",
    "Вьентьян": "Vientiane",
    "Луангпхабанг": "Luang Prabang",
    "Дели": "Delhi",
    "Мумбаи": "Bombay",
    "Джайпур": "Jaipur",
    "Варанаси": "Varanasi",
    "Агра": "Agra",
    "Катманду": "Katmandou",
    "Поркхара": "Pokhara",
    "Бхактапур": "Bhaktapur",
    "Виктория": "Victoria",
    "Маэ": "Mahé",
    "Праслин": "Praslin",
    "Порт-Луи": "Port-Louis",
    "Кюрпип": "Curepipe",
    "Мале": "Malé",
    "Адду": "Addu",
    "Коломбо": "Colombo",
    "Канди": "Kandy",
    "Нуваэлия": "Nuwara Eliya",
    "Мадрид": "Madrid",
    "Барселона": "Barcelone",
    "Севилья": "Séville",
    "Валенсия": "Valence",
    "Лиссабон": "Lisbonne",
    "Порту": "Porto",
    "Альгарве": "Algarve",
    "Рим": "Rome",
    "Миланы": "Milan",
    "Венеция": "Venise",
    "Флоренция": "Florence",
    "Неаполь": "Naples",
    "Париж": "Paris",
    "Канны": "Cannes",
    "Монако": "Monaco",
    "Лион": "Lyon",
    "Марсель": "Marseille",
    "Афины": "Athènes",
    "Салоники": "Thessalonique",
    "Санторини": "Santorin",
    "Крит": "Crète",
    "Загреб": "Zagreb",
    "Дубровник": "Dubrovnik",
    "Сплит": "Split",
    "София": "Sofia",
    "Варна": "Varna",
    "Пловдив": "Plovdiv",
    "Бухарест": "Bucarest",
    "Брашов": "Brașov",
    "Клуж-Напока": "Cluj-Napoca",
    "Будапешт": "Budapest",
    "Дебрецен": "Debrecen",
    "Сегед": "Szeged",
    "Прага": "Prague",
    "Брно": "Brno",
    "Чески-Крумлов": "Český Krumlov",
    "Вена": "Vienne",
    "Зальцбург": "Salzbourg",
    "Инсбрук": "Innsbruck",
    "Цюрих": "Zurich",
    "Люцерн": "Lucerne",
    "Базель": "Bâle",
    "Амстердам": "Amsterdam",
    "Роттердам": "Rotterdam",
    "Утрехт": "Utrecht",
    "Брюссель": "Bruxelles",
    "Антверпен": "Anvers",
    "Брюгге": "Bruges",
    "Лондон": "Londres",
    "Манчестер": "Manchester",
    "Эдинбург": "Édimbourg",
    "Дублин": "Dublin",
    "Корк": "Cork",
    "Осло": "Oslo",
    "Берген": "Bergen",
    "Тромсё": "Tromsø",
    "Стокгольм": "Stockholm",
    "Гётеборг": "Göteborg",
    "Мальме": "Malmö",
    "Хельсинки": "Helsinki",
    "Турку": "Turku",
    "Тампере": "Tampere",
    "Рейкьявик": "Reykjavik",
    "Акюрейри": "Akureyri",
    "Копенгаген": "Copenhague",
    "Орхус": "Aarhus",
    "Варшава": "Varsovie",
    "Краков": "Cracovie",
    "Вроцлав": "Wrocław",
    "Вильнюс": "Vilnius",
    "Каунас": "Kaunas",
    "Рига": "Riga",
    "Юрмала": "Jurmala",
    "Таллин": "Tallinn",
    "Тарту": "Tartu",
    "Берлин": "Berlin",
    "Мюнхен": "Munich",
    "Кёльн": "Cologne",
    "Нью-Йорк": "New York",
    "Лос-Анджелес": "Los Angeles",
    "Чикаго": "Chicago",
    "Майами": "Miami",
    "Лас-Вегас": "Las Vegas",
    "Ванкувер": "Vancouver",
    "Торонто": "Toronto",
    "Монреаль": "Montréal",
    "Мехико": "Mexico",
    "Канкун": "Cancún",
    "Плайя-дель-Кармен": "Playa del Carmen",
    "Рио-де-Жанейро": "Rio de Janeiro",
    "Сан-Паулу": "São Paulo",
    "Салвадор": "Salvador",
    "Буэнос-Айрес": "Buenos Aires",
    "Мендоза": "Mendoza",
    "Сантьяго": "Santiago",
    "Вальпараисо": "Valparaíso",
    "Лима": "Lima",
    "Куско": "Cusco",
    "Мачу-Пикчу": "Machu Picchu",
    "Кито": "Quito",
    "Гуаякиль": "Guayaquil",
    "Богота": "Bogota",
    "Медельин": "Medellín",
    "Каракас": "Caracas",
    "Марgarita": "Margarita",
    "Найроби": "Nairobi",
    "Момбаса": "Mombasa",
    "Дар-эс-Салам": "Dar es Salaam",
    "Камерон": "Cameron",
    "Кампала": "Kampala",
    "Форт-Портал": "Fort Portal",
    "Аддис-Абеба": "Addis-Abeba",
    "Адама": "Adama",
    "Габороне": "Gaborone",
    "Касане": "Kasane",
    "Хараре": "Harare",
    "Виктория-Фолс": "Chutes Victoria",
    "Виндхук": "Windhoek",
    "Суакопмунд": "Swakopmund",
    "Йоханнесбург": "Johannesburg",
    "Кейптаун": "Le Cap",
    "Претория": "Pretoria",
    "Антананариву": "Antananarivo",
    "Анциранана": "Antsiranana",
    "Алжир": "Alger",
    "Оран": "Oran",
    "Тунис": "Tunis",
    "Сусс": "Sousse",
    "Сфакс": "Sfax",
    "Касабланка": "Casablanca",
    "Марракеш": "Marrakech",
    "Фес": "Fès",
    "Сидней": "Sydney",
    "Мельбурн": "Melbourne",
    "Брисбен": "Brisbane",
    "Окленд": "Auckland",
    "Веллингтон": "Wellington",
    "Крайстчёрч": "Christchurch",
    "Сува": "Suva",
    "Нади": "Nadi",
    "Порт-Вила": "Port-Vila",
    "Луганвиль": "Luganville",
    "Сеул": "Séoul",
    "Пусан": "Busan",
    "Инчхон": "Incheon",
    "Токио": "Tokyo",
    "Осака": "Osaka",
    "Киото": "Kyoto",
    "Хиросима": "Hiroshima",
    "Сингапур": "Singapour",
    "Куала-Лумпур": "Kuala Lumpur",
    "Джорджтаун": "George Town",
    "Джакарта": "Jakarta",
    "Бали": "Bali",
    "Йогякарта": "Yogyakarta",
    "Манила": "Manille",
    "Себу": "Cebu",
    "Давао": "Davao",
    "Гонконг": "Hong Kong",
    "Тайбэй": "Taipei",
    "Гаосюн": "Kaohsiung",
    "Улан-Батор": "Oulan-Bator",
    "Тегеран": "Téhéran",
    "Исфахан": "Ispahan",
    "Тель-Авив": "Tel-Aviv",
    "Иерусалим": "Jérusalem",
    "Амман": "Amman",
    "Петра": "Pétra",
    "Бейрут": "Beyrouth",
    "Триполи": "Tripoli",
    "Эр-Рияд": "Riyad",
    "Джидда": "Djeddah",
    "Мекка": "La Mecque",
    "Доха": "Doha",
    "Кувейт": "Koweït City",
    "Маскат": "Mascate",
    "Салала": "Salalah"
  }
};

export function getCountryLabel(name: string, locale: string): string {
  const dict = countryLabels[locale as GeoLocale];
  return dict?.[name] ?? name;
}

export function getCityLabel(name: string, locale: string): string {
  const dict = cityLabels[locale as GeoLocale];
  return dict?.[name] ?? name;
}
