const copy = {
  ru: { subject: 'Вам написали на BlaBlaTravel', label: 'НОВОЕ СООБЩЕНИЕ', title: 'Ваше путешествие начинается с общения.', text: 'Вам пришло новое личное сообщение на BlaBlaTravel. Откройте переписку, чтобы прочитать его и ответить.', button: 'Открыть переписку', note: 'Новые знакомства. Общие маршруты. Больше впечатлений.', footer: 'Вы получили это письмо, потому что участник BlaBlaTravel написал вам. Не отвечайте на это письмо — ответьте в чате.', fallback: 'Если кнопка не работает, откройте ссылку:' },
  en: { subject: 'You have a new message on BlaBlaTravel', label: 'NEW MESSAGE', title: 'Every adventure starts with a conversation.', text: 'Someone sent you a private message on BlaBlaTravel. Open your conversation to read it and reply.', button: 'Open conversation', note: 'Meet new people. Share a route. Make memories.', footer: 'You received this email because a BlaBlaTravel member messaged you. Please reply in the chat, not to this email.', fallback: 'If the button does not work, open this link:' },
  de: { subject: 'Neue Nachricht auf BlaBlaTravel', label: 'NEUE NACHRICHT', title: 'Jede Reise beginnt mit einem Gespräch.', text: 'Du hast eine private Nachricht auf BlaBlaTravel erhalten. Öffne den Chat, um sie zu lesen und zu antworten.', button: 'Chat öffnen', note: 'Neue Menschen. Gemeinsame Wege. Besondere Erinnerungen.', footer: 'Du erhältst diese E-Mail, weil dir ein Mitglied von BlaBlaTravel geschrieben hat. Antworte bitte im Chat, nicht auf diese E-Mail.', fallback: 'Falls die Schaltfläche nicht funktioniert, öffne diesen Link:' },
  es: { subject: 'Tienes un nuevo mensaje en BlaBlaTravel', label: 'NUEVO MENSAJE', title: 'Cada aventura empieza con una conversación.', text: 'Has recibido un mensaje privado en BlaBlaTravel. Abre la conversación para leerlo y responder.', button: 'Abrir conversación', note: 'Conoce gente. Comparte rutas. Crea recuerdos.', footer: 'Recibes este correo porque un miembro de BlaBlaTravel te ha escrito. Responde en el chat, no a este correo.', fallback: 'Si el botón no funciona, abre este enlace:' },
  pt: { subject: 'Você recebeu uma mensagem no BlaBlaTravel', label: 'NOVA MENSAGEM', title: 'Toda aventura começa com uma conversa.', text: 'Você recebeu uma mensagem privada no BlaBlaTravel. Abra a conversa para ler e responder.', button: 'Abrir conversa', note: 'Conheça pessoas. Compartilhe caminhos. Crie memórias.', footer: 'Você recebeu este email porque alguém do BlaBlaTravel escreveu para você. Responda pelo chat, não por email.', fallback: 'Se o botão não funcionar, abra este link:' },
  fr: { subject: 'Vous avez un nouveau message sur BlaBlaTravel', label: 'NOUVEAU MESSAGE', title: 'Chaque aventure commence par une conversation.', text: 'Vous avez reçu un message privé sur BlaBlaTravel. Ouvrez la conversation pour le lire et y répondre.', button: 'Ouvrir la conversation', note: 'Des rencontres. Des itinéraires partagés. Des souvenirs.', footer: 'Vous recevez cet email car un membre de BlaBlaTravel vous a écrit. Répondez dans le chat, pas à cet email.', fallback: 'Si le bouton ne fonctionne pas, ouvrez ce lien :' },
} as const;

export function messageEmail(locale: string, conversationId: string) {
  if (!/^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i.test(conversationId)) throw new Error('Invalid conversation id');
  const language = Object.hasOwn(copy, locale) ? locale as keyof typeof copy : 'en';
  const t = copy[language];
  const url = `https://blablatravel.com/${language}/chat/${conversationId}`;
  const html = `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t.subject}</title></head>
<body style="margin:0;padding:0;background:#f0f4f1;font-family:Arial,Helvetica,sans-serif;color:#182d27">
<div style="display:none;max-height:0;overflow:hidden;opacity:0">${t.subject}. ${t.button}.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f1"><tr><td align="center" style="padding:32px 16px">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" style="width:100%;max-width:560px;background:#ffffff;border:1px solid #dee8e1;border-radius:24px;overflow:hidden">
<tr><td style="background:#142d25;padding:28px 32px;color:#ffffff"><a href="https://blablatravel.com/${language}" style="font-size:25px;font-weight:800;letter-spacing:-1px;color:#ffffff;text-decoration:none">BlaBla<span style="color:#a8e6ba">Travel</span></a><div style="padding-top:20px;color:#a8e6ba;font-size:12px;letter-spacing:2px">● &nbsp; ─ ─ ─ ─ ─ &nbsp; ✈ &nbsp; ─ ─ ─ ─ ─ &nbsp; ●</div></td></tr>
<tr><td style="padding:36px 32px 32px"><p style="margin:0 0 18px;color:#237b51;font-size:11px;letter-spacing:2px;font-weight:bold">${t.label}</p><h1 style="margin:0 0 18px;font-size:30px;line-height:1.2;letter-spacing:-0.8px">${t.title}</h1><p style="margin:0 0 28px;font-size:16px;line-height:1.7;color:#52665d">${t.text}</p>
<table role="presentation" cellpadding="0" cellspacing="0"><tr><td bgcolor="#237b51" style="border-radius:12px"><a href="${url}" style="display:inline-block;padding:17px 26px;border:1px solid #237b51;border-radius:12px;color:#ffffff;font-size:16px;font-weight:bold;text-decoration:none;mso-padding-alt:0"><!--[if mso]><i style="mso-font-width:150%;mso-text-raise:24pt" hidden>&emsp;</i><![endif]-->${t.button} &nbsp; →<!--[if mso]><i style="mso-font-width:150%" hidden>&emsp;</i><![endif]--></a></td></tr></table>
<p style="margin:30px 0 0;padding-top:22px;border-top:1px solid #e7eee9;font-size:13px;line-height:1.7;color:#6a7d72">${t.note}</p></td></tr></table>
<table role="presentation" width="560" cellpadding="0" cellspacing="0" style="width:100%;max-width:560px"><tr><td style="padding:22px 16px;color:#718279;font-size:12px;line-height:1.7"><p style="margin:0 0 12px">${t.footer}</p><p style="margin:0">${t.fallback}<br><a href="${url}" style="color:#237b51;word-break:break-all">${url}</a></p></td></tr></table>
</td></tr></table></body></html>`;
  return { subject: t.subject, html, text: `${t.subject}\n\n${t.title}\n\n${t.text}\n\n${t.button}: ${url}\n\n${t.footer}` };
}
